veclist <- list(x=1:5, y=2:6, z=3:7)
sapply(veclist, length)
all(sapply(veclist,length) == 5)
sapply(veclist, sum)
veclist$norms <- rnorm(10)
pupae <- read.csv("pupae.csv")
pupae_sp <- split(pupae, pupae$CO2_treatment)
lapply(pupae_sp, function(x)t.test(PupalWeight ~ T_treatment, data=x))
